### ISSUE TITLE
README Updates

### ISSUE THREAD

**Issue by clunietp** [johannestang/yolo_service#2]
Thank you for this image!

README states:
` YOLO9000 covering more than 9000 classes listed here. Tag: yolo90000. `

Tag should be `yolo9000`

Also, some simple python examples may be helpful, here's one for POST:

    import requests
    import json

    with open('test.jpg', 'rb') as f:
        r = requests.post("http://localhost:9999/detect",files={'image_file': f},timeout=60, data={'threshold':0.25})
    if r.status_code == 200:
        data = json.loads(r.text)
        print(data)

**Comment by johannestang** [comment]
Thanks for letting me know. I've corrected the typo, and I've also added some examples - good idea.
