### ISSUE TITLE
Yolov4 upgrade

### ISSUE THREAD

**Issue by samux87** [johannestang/yolo_service#3]
I would like to use this repo but with yolov4, is it possible? 

I tried to change the dockerfile in this way:

from this: RUN git clone -n https://github.com/AlexeyAB/darknet.git
to this: RUN git clone https://github.com/AlexeyAB/darknet.git
and comment the line 
#RUN git checkout 4c315ea26b56c2bf20ebc240d94386c6e3cc83db

but the image wants to start.

Do you have any suggestions?

Thank you,
Sam.

**Comment by johannestang** [comment]
It is possible, but it requires a bit more than you suggest because of some incompatibilities in the provided python library. I've updated the repo to use the latest version of darknet and support yolov4. I haven't done a lot of testing, so let me know if you encounter any issues.

**Comment by samux87** [comment]
Ok, thank you for the help! 
I will try it out.

Sam.

**Comment by samux87** [comment]
I got this error
Step 11/40 : RUN git checkout 38a164bcb9e017f8c9c3645a39419320e217545e
 ---> Running in 96c66091ec59
fatal: reference is not a tree: 38a164bcb9e017f8c9c3645a39419320e217545e
The command '/bin/sh -c git checkout 38a164bcb9e017f8c9c3645a39419320e217545e' returned a non-zero code: 128

when I did:
docker build -t testimage .

S.

**Comment by johannestang** [comment]
I'm afraid I cannot replicate your problem. The build works fine on both my machine and DockerHub's build service, so I have to assume the problem is in your environment. Could you perhaps try it on a different machine? Or try running the git commands locally on your machine (outside Docker) to rule out any connectivity problems?

**Comment by samux87** [comment]
Ok, I change a few things and now it works with my custom yolov4 model.

In the end, I just cloned the darknet repo and I changed a few lines in order to copy my model instead of yours in the docker file.

Thank you again for your help, I learned a lot from your article and your code.
Sam.
